### ISSUE TITLE
啓動報錯

### ISSUE THREAD

**Issue by w350727743** [ItGarbager/aimcf_yolov5#7]
運行main.py后如下報錯，up主可以幫忙看下什麽原因嗎？謝謝！
罗技驱动加载状态: 0
飞易来/文盒驱动加载状态: 1
进程 auto_aim 启动 ...
进程 img_show 启动 ...
进程 img_init 启动 ...
模型加载完毕 ...
Process Process-3:
Traceback (most recent call last):
  File "D:\ITTools\anaconda\envs\pytorch\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\ITTools\anaconda\envs\pytorch\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\ITTools\pythonworkspace\aimcf_yolov5-2\main.py", line 56, in img_init
    model, device, half, stride, names, imgsz = load_model_infos()
  File "D:\ITTools\pythonworkspace\aimcf_yolov5-2\tools\get_model.py", line 22, in load_model_infos
    model(torch.zeros(1, 3, *imgsz).to(device).type_as(next(model.parameters())))  # run once
  File "D:\ITTools\anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\ITTools\pythonworkspace\aimcf_yolov5-2\models\yolo.py", line 126, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "D:\ITTools\pythonworkspace\aimcf_yolov5-2\models\yolo.py", line 149, in _forward_once
    x = m(x)  # run
  File "D:\ITTools\anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\ITTools\anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\upsampling.py", line 154, in forward
    recompute_scale_factor=self.recompute_scale_factor)
  File "D:\ITTools\anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'

**Comment by ItGarbager** [comment]
![image](https://user-images.githubusercontent.com/95277218/179528747-e5d81a2c-a027-4011-aae8-b745523173be.png)
> return F.interpolate(input, self.size, self.scale_factor, self.mode, self.align_corners)
按照图中的解决方法尝试下

**Comment by w350727743** [comment]
谢谢大佬，解决了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ItGarbager/aimcf_yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月18日(星期一) 晚上10:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ItGarbager/aimcf_yolov5] 啓動報錯 (Issue #7)





 

  
return F.interpolate(input, self.size, self.scale_factor, self.mode, self.align_corners)
 按照图中的解决方法尝试下
